services:
  web_api:
    build: ./
    container_name: web_api
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db_psql;Port=5432;Database=shopping_market;Username=postgres;Password=postgres;
      AllowedHosts: "*"
      BearerKey: SUPER_SECRET_DEVELOPMENT_KEY_77984621
    depends_on:
      - db_psql
    ports:
      - 80:8080
    mem_limit: 300M
    cpus: 0.5
    networks:
      - development_network

  mongodb:
    image: mongodb/mongodb-community-server:6.0.5-ubuntu2204-20230514T051156Z
    container_name: mongodb
    restart: no

    environment:
      MONGODB_INITDB_ROOT_USERNAME: mongodbuser
      MONGODB_INITDB_ROOT_PASSWORD: mongodbxxsenha314forte

    volumes:
      - $VOLUMES/.mongodb:/data/db

    ports:
      - 27017:27017

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

    networks:
      - development_network

networks:
  development_network:
    driver: bridge